
# Shell Enhancements and Utilities
brew "zsh" # Shell
brew "fzf" # Fuzzy Finder
brew "z" # Directory Jumper
brew "tldr" # Simplified and community-driven man pages
brew "sd" # Intuitive find & replace CLI
brew "neovim" # Text Editor
brew "fd" # File Search
brew "translate-shell" # Command-line translator
brew "ripgrep" # Advanced text search tool
brew "lsd" # Modern ls replacement
brew "git-delta" # Modern file and git diff

# Development Tools
brew "shellcheck" # Shell Script Analysis Tool
brew "gh" # GitHub CLI
brew "awscli" # AWS CLI
brew "aws-sam-cli" # AWS Serverless Application Model CLI
brew "libpq" # PostgreSQL Library
brew "sdkman-cli" # SDK Management
brew "pyenv" # Python Version Management

# Data Processing
brew "jq" # JSON Processor
brew "python-yq" # YAML Processor (also supports XML as xq)
brew "yj" # YAML and JSON Converter
brew "jc" # unix tool output to json converter
brew "gron" # Make JSON Greppable
brew "visidata" # Data Explorer
brew "gnuplot" # Plotting Utility
brew "miller" # Text Data Processing Tool
brew "harelba/q/q" # SQL-like queries on CSVs

# Image Processing
brew "tesseract" # OCR Reader
brew "tesseract-lang" # OCR Language Packs
brew "pngpaste" # Clipboard Image Saving
brew "thezoraiz/ascii-image-converter/ascii-image-converter" # ASCII Image Conversion
brew "imagemagick" # Image Processing Tool

# File Managament
brew "dbxcli" # Dropbox CLI
brew "qrcp" # File Transfer via QR Codes
brew "qpdf" # PDF Processing Tool
brew "rnr" # File Renaming Tool

# System and Performance Monitoring
brew "btop" # System Monitoring

# Miscellaneous Utilities
brew "qrencode" # QR Code Generation
brew "d2" # Diagram Scripting Language
brew "countdown" # Countdown Timer
brew "utimer" # Command-line Timer

# Casks
cask "wezterm"
cask "rectangle"
cask "clipy"
cask "keepassxc"
cask "visual-studio-code"
cask "lunar"
