tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "thezoraiz/ascii-image-converter"
tap "eddieantonio/eddieantonio"

brew "zsh"
brew "docker"
brew "gawk"
brew "sd"
brew "grep"
brew "httpie"
brew "jq"
brew "yq"
brew "pngpaste" #save images from clipboard
brew "pyenv"
brew "ripgrep"
brew "tree"
brew "eddieantonio/eddieantonio/imgcat"
brew "thezoraiz/ascii-image-converter/ascii-image-converter"
brew "gron" #json to discrete form
brew "qrcp" #send files through qr codes
brew "yq" #converts yaml, json
brew "htop" #process monitor
brew "shellcheck"

cask "iterm2"
cask "clipy"
cask "rectangle"
cask "keepassxc"


# # gotta check those:
# brew "ccat"
# brew "cmatrix"
# brew "fswatch"
# brew "fzy"
# brew "bat"
# brew "git-delta"
# brew "glances"
# brew "glow"
# brew "gnutls"
# brew "navi"
# brew "exa"
# brew "graphviz"
# brew "gh", link: false
# brew "hyperkit" 
# brew "kubernetes-cli"
# brew "mdp"
# brew "minikube"
# brew "hugo"
# brew "kotlin"
# brew "task"
# brew "tfenv"
# brew "thefuck"
# brew "tmux"
# brew "slides"
# cask "google-cloud-sdk"
# cask "copyq" # check it as clipy alternative

