tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"
tap "thezoraiz/ascii-image-converter"
tap "eddieantonio/eddieantonio"
tap "mongodb/brew"
tap "idleberg/dbxcli"
tap "sdkman/tap"
tap "aws/tap"
tap "saulpw/vd"

brew "zsh"
brew "fzf"
brew "z"
brew "tldr"
brew "howdoi"
brew "docker"
brew "mongosh"
brew "awscli"
brew "sd"
brew "neovim"

brew "pngpaste" #save images from clipboard
brew "pyenv"
brew "ripgrep"
brew "tree"
brew "translate-shell"

brew "qrencode"

brew "btop" #process manager
brew "shellcheck"
brew "awscli"
brew "aws-sam-cli"

brew "libpq"
brew "dbxcli"

brew "diff-so-fancy"
brew "sdkman-cli"
brew "rnr" #mass rename files

#data
brew "jq"
brew "yq"
brew "yj"
brew "gron" #json to discrete form
brew "visidata"
brew "gnupot" #plots in terminal
brew "miller" #text data processor

#media
brew "eddieantonio/eddieantonio/imgcat"
brew "thezoraiz/ascii-image-converter/ascii-image-converter"
brew "imagemagick" #image processor, invoked as 'magick'

#utils
brew "utimer"
brew "qpdf"
brew "qrcp" #send files through qr codes
brew "tesseract" #ocr reader
brew "tesseract-lang" #language pack to ocr

cask "iterm2"
cask "clipy"
cask "rectangle"
cask "keepassxc"
cask "visual-studio-code"
cask "font-hack"
cask "lunar"
